# Generated by Django 4.0.3 on 2022-05-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_policestation_delete_thana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='users.division'),
        ),
    ]
