# Generated by Django 4.0.3 on 2022-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_district_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
