# Generated by Django 4.0.5 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_city_id_alter_district_id_alter_division_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
    ]
