# Generated by Django 4.0.3 on 2022-06-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherlisting',
            old_name='teacher',
            new_name='user',
        ),
    ]
