# Generated by Django 4.0.3 on 2022-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_rename_teacher_teacherlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlisting',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
