# Generated by Django 4.0.5 on 2022-06-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_teacherlisting_video_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
