# Generated by Django 4.0.5 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_teacherlisting_id_alter_teacherpremium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlisting',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherpremium',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
    ]
