# Generated by Django 4.0.5 on 2022-07-12 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_teacherlisting_id_alter_teacherpremium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherpremium',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
