# Generated by Django 4.0.3 on 2022-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='room',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='categories.category'),
        ),
    ]
