# Generated by Django 4.0.5 on 2022-07-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Room Admin'),
        ),
        migrations.AddField(
            model_name='room',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='categories.category'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(through='room.RoomUser', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('room', 'user')},
        ),
    ]
