# Generated by Django 4.0.5 on 2022-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_id_alter_roomuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
    ]
