# Generated by Django 4.0.5 on 2022-08-23 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_alter_roomuser_room_alter_roomuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomuser', to='room.room'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
