# Generated by Django 4.0.3 on 2022-04-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomfeepayment',
            name='room_user_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_fee_payment', to='payment.roomuserfee'),
        ),
    ]
