# Generated by Django 4.0.5 on 2022-07-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuserfee',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='roomfeepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='roomfeepayment',
            name='room_user_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_fee_payment', to='payment.roomuserfee'),
        ),
        migrations.AddField(
            model_name='roomfee',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.fee'),
        ),
        migrations.AddField(
            model_name='roomfee',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='roomfee',
            name='room_user',
            field=models.ManyToManyField(blank=True, through='payment.RoomUserFee', to='room.roomuser', verbose_name='Applies To'),
        ),
        migrations.AddField(
            model_name='payment',
            name='room_user_fee',
            field=models.ManyToManyField(related_name='payment', through='payment.RoomFeePayment', to='payment.roomuserfee'),
        ),
        migrations.AlterUniqueTogether(
            name='roomuserfee',
            unique_together={('room_user', 'room_fee')},
        ),
    ]
