# Generated by Django 4.0.5 on 2022-07-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuserfee',
            name='room_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user_fees', to='payment.roomfee'),
        ),
        migrations.AlterField(
            model_name='roomuserfee',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user_fees', to='room.roomuser'),
        ),
    ]
