# Generated by Django 4.0.5 on 2022-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_roomuserfee_room_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='room_user_fee',
            field=models.ManyToManyField(related_name='payments', through='payment.RoomFeePayment', to='payment.roomuserfee'),
        ),
    ]
