# Generated by Django 4.0.5 on 2022-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_fee_id_alter_payment_id_alter_roomfee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomfee',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomfeepayment',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomuserfee',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
    ]
