# Generated by Django 4.0.5 on 2022-07-12 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingresponse_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingresponse',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
