# Generated by Django 4.0.5 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingresponse_options_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingresponse',
            name='id',
            field=models.UUIDField(default='f2d8ed1043ec49d18d0221c395339445', editable=False, primary_key=True, serialize=False),
        ),
    ]
