# Generated by Django 4.0.5 on 2022-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_id_alter_bookingresponse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default='e87ef7d321c345ceafaad230e5fab420', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingresponse',
            name='id',
            field=models.UUIDField(default='e87ef7d321c345ceafaad230e5fab420', editable=False, primary_key=True, serialize=False),
        ),
    ]
