# Generated by Django 4.0.3 on 2022-05-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
