# Generated by Django 4.0.3 on 2022-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_grades_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
