# Generated by Django 4.0.3 on 2022-05-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_grades_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='categories.category'),
        ),
    ]
