# Generated by Django 4.0.5 on 2022-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default='997236f535494ec08ef66987daaee666', editable=False, primary_key=True, serialize=False),
        ),
    ]
