# Generated by Django 4.0.5 on 2022-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_grade_created_at_grade_is_active_grade_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default='e87ef7d321c345ceafaad230e5fab420', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.UUIDField(default='e87ef7d321c345ceafaad230e5fab420', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default='e87ef7d321c345ceafaad230e5fab420', editable=False, primary_key=True, serialize=False),
        ),
    ]
