# Generated by Django 4.0.5 on 2022-07-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
        migrations.AddField(
            model_name='link',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
        migrations.AddField(
            model_name='examsubmissionmark',
            name='exam_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.examsubmission'),
        ),
        migrations.AddField(
            model_name='examsubmissionfile',
            name='exam_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submission_files', to='task.examsubmission'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='task.exam'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='examfile',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task.exam'),
        ),
        migrations.AddField(
            model_name='examcomment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.exam'),
        ),
        migrations.AddField(
            model_name='examcomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionmark',
            name='assignment_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionfile',
            name='assignment_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_files', to='task.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='task.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='assignmentfile',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('room_user', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('room_user', 'assignment')},
        ),
    ]
