# Generated by Django 4.0.3 on 2022-04-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('task', '0002_remove_assignmentcomment_room_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notecomment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='room_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='examcomment',
            name='room_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='room_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
    ]
