# Generated by Django 4.0.5 on 2022-07-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionmark',
            name='assignment_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='task.assignmentsubmission'),
        ),
    ]
