# Generated by Django 4.0.5 on 2022-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_assignmentsubmissionmark_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionmark',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examsubmissionmark',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
