# Generated by Django 4.0.5 on 2022-07-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_assignmentsubmissionmark_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmissionmark',
            name='exam_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='task.examsubmission'),
        ),
    ]
