# Generated by Django 4.0.3 on 2022-04-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('task', '0005_alter_assignmentcomment_user_alter_examcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='room_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='room_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
    ]
