# Generated by Django 4.0.3 on 2022-04-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('task', '0006_alter_assignmentsubmission_room_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='task.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomuser'),
        ),
    ]
