# Generated by Django 4.0.3 on 2022-04-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('task', '0007_alter_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='task.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('room_user', 'assignment')},
        ),
    ]
