# Generated by Django 4.0.3 on 2022-04-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('task', '0008_alter_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('room_user', 'exam')},
        ),
    ]
