# Generated by Django 4.0.3 on 2022-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_examsubmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
