# Generated by Django 4.0.5 on 2022-07-13 18:01

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_id_alter_roomuser_id'),
        ('task', '0018_alter_assignment_id_alter_assignmentcomment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(default=users.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
