# Generated by Django 4.0.5 on 2022-07-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmeeting',
            name='roomuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.roomuser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
    ]
