# Generated by Django 4.0.5 on 2022-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lobby_name',
            field=models.CharField(default='openlobby', max_length=255),
            preserve_default=False,
        ),
    ]
