# Generated by Django 4.0.5 on 2022-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_lobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='lobby_name',
            field=models.CharField(default='82ae9c86', max_length=255),
        ),
    ]
