# Generated by Django 4.0.5 on 2022-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_meeting_id_alter_trialmeeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.CharField(default='84ce30835889481fb25911f04b7dae1b', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trialmeeting',
            name='id',
            field=models.CharField(default='84ce30835889481fb25911f04b7dae1b', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
