# Generated by Django 4.0.5 on 2022-07-12 20:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_alter_meeting_id_alter_trialmeeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.CharField(default=users.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trialmeeting',
            name='id',
            field=models.CharField(default=users.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
